"""initial_schema

Revision ID: b6be05ce10f5
Revises: 
Create Date: 2026-06-07 15:21:17.775823
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6be05ce10f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('invitee_email', sa.String(length=320), nullable=True),
    sa.Column('invitee_phone', sa.String(length=20), nullable=True),
    sa.Column('invitee_id', sa.UUID(), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('points_awarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('inviter_id', 'invitee_email', name='uq_invitation_email'),
    sa.UniqueConstraint('inviter_id', 'invitee_phone', name='uq_invitation_phone')
    )
    op.create_table('notification_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('segment_level_id', sa.UUID(), nullable=True),
    sa.Column('segment_region_id', sa.UUID(), nullable=True),
    sa.Column('segment_role', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['segment_level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['segment_region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('idempotency_key', name='uq_point_transactions_idempotency')
    )
    op.drop_table('referrals')
    op.add_column('activities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('activities', 'action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('activities', 'points_awarded',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('activities', 'reference_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('activities', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_activities_action'), table_name='activities')
    op.drop_index(op.f('idx_activities_created'), table_name='activities')
    op.drop_index(op.f('idx_activities_user'), table_name='activities')
    op.alter_column('badges', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('badges', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'achievement'::text"))
    op.alter_column('badges', 'rarity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'common'::text"))
    op.alter_column('badges', 'criteria_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('badges', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('badges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('badges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('content', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('content', 'content_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('content', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('content', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('content', 'points_per_share',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('content', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('content', 'total_shares',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('content', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('content', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('content_shares', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('content_shares', 'shared_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_content_shares_user'), table_name='content_shares')
    op.alter_column('event_participants', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'registered'::text"))
    op.alter_column('event_participants', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('event_participants_event_id_user_id_key'), 'event_participants', type_='unique')
    op.add_column('events', sa.Column('checkin_code', sa.String(length=20), nullable=True))
    op.add_column('events', sa.Column('checkin_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('checkin_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('checkin_radius_meters', sa.Integer(), nullable=True))
    op.alter_column('events', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'meeting'::text"))
    op.alter_column('events', 'location_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('events', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('events', 'points_reward',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_events_active'), table_name='events', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_events_start'), table_name='events')
    op.add_column('levels', sa.Column('min_missions_completed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('levels', sa.Column('min_referrals_active', sa.Integer(), server_default='0', nullable=False))
    op.add_column('levels', sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('levels', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('levels', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('levels', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.alter_column('levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('levels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('levels', 'perks')
    op.add_column('mission_categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('mission_categories', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('mission_categories', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('mission_categories', 'icon',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('mission_categories', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.alter_column('mission_categories', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('mission_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('missions', sa.Column('recurrence', sa.String(length=20), server_default='ONE_TIME', nullable=False))
    op.add_column('missions', sa.Column('max_daily_completions', sa.Integer(), server_default='0', nullable=False))
    op.add_column('missions', sa.Column('max_submissions', sa.Integer(), server_default='3', nullable=False))
    op.add_column('missions', sa.Column('is_self_declared', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('missions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('missions', 'action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('missions', 'xp_reward',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('missions', 'required_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('missions', 'requires_verification',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('missions', 'verification_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('missions', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('missions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('missions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('missions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('missions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_missions_active'), table_name='missions', postgresql_where='(is_active = true)')
    op.drop_column('missions', 'mission_type')
    op.add_column('notifications', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'info'::text"))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_notifications_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.create_foreign_key(None, 'notifications', 'notification_campaigns', ['campaign_id'], ['id'])
    op.add_column('profiles', sa.Column('level_pending_approval', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('profiles', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.alter_column('profiles', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('profiles', 'cpf',
               existing_type=sa.TEXT(),
               type_=sa.String(length=14),
               existing_nullable=True)
    op.alter_column('profiles', 'gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('profiles', 'neighborhood',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('profiles', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('profiles', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True,
               existing_server_default=sa.text("'SP'::text"))
    op.alter_column('profiles', 'zip_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('profiles', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('profiles', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("'participant'::text"))
    op.alter_column('profiles', 'referral_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('profiles', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_profiles_email'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_level'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_referral_code'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_region'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_total_points'), table_name='profiles')
    op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')
    op.alter_column('regions', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('regions', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('regions', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('regions', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('regions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('regions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('regions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('regions', 'geojson')
    op.alter_column('user_badges', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_badges', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('user_badges_user_id_badge_id_key'), 'user_badges', type_='unique')
    op.add_column('user_missions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('user_missions', sa.Column('submission_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_missions', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_missions', sa.Column('rejected_reason', sa.Text(), nullable=True))
    op.alter_column('user_missions', 'progress_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_missions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("'in_progress'::text"))
    op.alter_column('user_missions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_missions', 'points_awarded',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_user_missions_status'), table_name='user_missions')
    op.drop_constraint(op.f('user_missions_user_id_mission_id_key'), 'user_missions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_missions_user_id_mission_id_key'), 'user_missions', ['user_id', 'mission_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_missions_status'), 'user_missions', ['user_id', 'status'], unique=False)
    op.alter_column('user_missions', 'points_awarded',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_missions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_missions', 'status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'in_progress'::text"))
    op.alter_column('user_missions', 'progress_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('user_missions', 'rejected_reason')
    op.drop_column('user_missions', 'submitted_at')
    op.drop_column('user_missions', 'submission_count')
    op.drop_column('user_missions', 'notes')
    op.create_unique_constraint(op.f('user_badges_user_id_badge_id_key'), 'user_badges', ['user_id', 'badge_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_badges', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_badges', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('regions', sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('regions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('regions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regions', 'state',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('regions', 'city',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('regions', 'slug',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('regions', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_index(op.f('idx_profiles_total_points'), 'profiles', [sa.literal_column('total_points DESC')], unique=False)
    op.create_index(op.f('idx_profiles_region'), 'profiles', ['region_id'], unique=False)
    op.create_index(op.f('idx_profiles_referral_code'), 'profiles', ['referral_code'], unique=False)
    op.create_index(op.f('idx_profiles_level'), 'profiles', ['current_level_id'], unique=False)
    op.create_index(op.f('idx_profiles_email'), 'profiles', ['email'], unique=False)
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('profiles', 'referral_code',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'role',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'participant'::text"))
    op.alter_column('profiles', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('profiles', 'zip_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'state',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'SP'::text"))
    op.alter_column('profiles', 'city',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'neighborhood',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'cpf',
               existing_type=sa.String(length=14),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.String(length=320),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('profiles', 'level_pending_approval')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_unread'), 'notifications', ['user_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'info'::text"))
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('notifications', 'campaign_id')
    op.add_column('missions', sa.Column('mission_type', sa.TEXT(), server_default=sa.text("'one_time'::text"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_missions_active'), 'missions', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('missions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('missions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('missions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('missions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('missions', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('missions', 'verification_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('missions', 'requires_verification',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('missions', 'required_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('missions', 'xp_reward',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('missions', 'action_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('missions', 'title',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('missions', 'is_self_declared')
    op.drop_column('missions', 'max_submissions')
    op.drop_column('missions', 'max_daily_completions')
    op.drop_column('missions', 'recurrence')
    op.alter_column('mission_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mission_categories', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('mission_categories', 'color',
               existing_type=sa.String(length=7),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mission_categories', 'icon',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mission_categories', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('mission_categories', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('mission_categories', 'updated_at')
    op.add_column('levels', sa.Column('perks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.alter_column('levels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('levels', 'color',
               existing_type=sa.String(length=7),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('levels', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('levels', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('levels', 'requires_approval')
    op.drop_column('levels', 'min_referrals_active')
    op.drop_column('levels', 'min_missions_completed')
    op.create_index(op.f('idx_events_start'), 'events', ['start_datetime'], unique=False)
    op.create_index(op.f('idx_events_active'), 'events', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('events', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'points_reward',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'city',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'location_name',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'event_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'meeting'::text"))
    op.alter_column('events', 'title',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('events', 'checkin_radius_meters')
    op.drop_column('events', 'checkin_end')
    op.drop_column('events', 'checkin_start')
    op.drop_column('events', 'checkin_code')
    op.create_unique_constraint(op.f('event_participants_event_id_user_id_key'), 'event_participants', ['event_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('event_participants', 'registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_participants', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'registered'::text"))
    op.create_index(op.f('idx_content_shares_user'), 'content_shares', ['user_id'], unique=False)
    op.alter_column('content_shares', 'shared_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('content_shares', 'platform',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('content', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('content', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('content', 'total_shares',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('content', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('content', 'points_per_share',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('content', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('content', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('content', 'content_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('content', 'title',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('badges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('badges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('badges', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('badges', 'criteria_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('badges', 'rarity',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'common'::text"))
    op.alter_column('badges', 'category',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'achievement'::text"))
    op.alter_column('badges', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_activities_user'), 'activities', ['user_id'], unique=False)
    op.create_index(op.f('idx_activities_created'), 'activities', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_activities_action'), 'activities', ['action_type'], unique=False)
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activities', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('activities', 'reference_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activities', 'points_awarded',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('activities', 'action_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('activities', 'updated_at')
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('referrer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('referred_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('points_awarded', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'rewarded'::text])", name=op.f('referrals_status_check')),
    sa.ForeignKeyConstraint(['referred_id'], ['profiles.id'], name=op.f('referrals_referred_id_fkey')),
    sa.ForeignKeyConstraint(['referrer_id'], ['profiles.id'], name=op.f('referrals_referrer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('referrals_pkey')),
    sa.UniqueConstraint('referrer_id', 'referred_id', name=op.f('referrals_referrer_id_referred_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('point_transactions')
    op.drop_table('notification_campaigns')
    op.drop_table('invitations')
    op.drop_table('consents')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
